name: Azure Workflow
env:
  TERRAFORM_VERSION: '1.9.5'
  TERRAFORM_FILES_PATH: './calling_modules'

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: environment
        options:
          - dev
          - pro

permissions:
  contents: read
  issues: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Run Terraform Plan
        uses: ./.github/actions/terraform-plan
        with:
          tf-version: ${{ env.TERRAFORM_VERSION }}                    # Specifies version of Terraform to use
          tf_vars_file: "tfvars-file-name"                            # Specifies Terraform TFVARS file name inside module path
          tf_key: "state-file-name"                                   # Specifies name for terraform state file and plan artifact
          az_resource_group: "resource-group-name"                    # AZURE Resource Group hosting terraform backend storage account
          working-directory: ${{ env.TERRAFORM_FILES_PATH }}          # AZURE Files path
          az_storage_acc: ${{ vars.STORAGE_ACCOUNT_NAME }}            # AZURE terraform backend storage account
          az_container_name: ${{ vars.CONTAINER_NAME }}               # AZURE storage container hosting state files
          arm_client_id: ${{ secrets.CLIENT_ID }}                     # ARM Client ID 
          arm_client_secret: ${{ secrets.CLIENT_SECRET }}             # ARM Client Secret
          arm_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}         # ARM Subscription ID
          arm_tenant_id: ${{ secrets.TENANT_ID }}                     # ARM Tenant ID
